#!/bin/bash
# Script for user data
# install httpd (Linux 2 version)
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
echo "<h1>Hello Baby from $(hostname -f)</h1>" > /var/www/html/index.html
